package dao;

import model.Student;
import util.DatabaseConnection;
import java.sql.*;
import util.PasswordUtil;
import java.util.ArrayList;
import java.util.List;

public class StudentDao {

    // ── READ ──────────────────────────────────────────────────────────────────

    /**
     * Loads a student by username, including password for login verification.
     */
    public Student getStudentByUsername(String username) {
        String sql = "SELECT p.*, s.course, s.roomId, s.enrollment_date, s.status, s.username, s.password, s.regNumber " +
             "FROM person p JOIN student s ON p.id = s.id WHERE s.username = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, username);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                Student student = new Student(
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getInt("age"),
                    rs.getString("course")
                );
                student.setEmail(rs.getString("email"));
                student.setPhone(rs.getString("phone"));
                student.setRoomId(rs.getString("roomId"));
                student.setStatus(rs.getString("status"));
                student.setUsername(rs.getString("username"));
                student.setPassword(rs.getString("password")); // needed for login check
                student.setRegNumber(rs.getString("regNumber"));
                return student;
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Loads a student by their numeric ID.
     */
    public Student getStudentById(String id) {
        String sql = "SELECT p.*, s.course, s.roomId, s.status, s.username, s.regNumber " +
                     "FROM person p JOIN student s ON p.id = s.id WHERE p.id = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, id);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                Student student = new Student(
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getInt("age"),
                    rs.getString("course")
                );
                student.setEmail(rs.getString("email"));
                student.setPhone(rs.getString("phone"));
                student.setRoomId(rs.getString("roomId"));
                student.setStatus(rs.getString("status"));
                student.setUsername(rs.getString("username"));
                return student;
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Returns all students for the admin table view.
     */
    public List<Student> getAllStudents() {
        List<Student> list = new ArrayList<>();
        String sql = "SELECT p.*, s.course, s.roomId, s.status, s.username, s.regNumber " +
                     "FROM person p JOIN student s ON p.id = s.id";

        try (Connection conn = DatabaseConnection.getConnection();
             Statement stmt  = conn.createStatement();
             ResultSet rs    = stmt.executeQuery(sql)) {

            while (rs.next()) {
                Student student = new Student(
                    rs.getString("id"),
                    rs.getString("name"),
                    rs.getInt("age"),
                    rs.getString("course")
                );
                student.setEmail(rs.getString("email"));
                student.setPhone(rs.getString("phone"));
                student.setRoomId(rs.getString("roomId"));
                student.setStatus(rs.getString("status"));
                student.setUsername(rs.getString("username"));
                student.setRegNumber(rs.getString("regNumber"));
                list.add(student);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    // ── CREATE ────────────────────────────────────────────────────────────────

    /**
     * Inserts into both person and student tables inside a transaction.
     * ID is auto-generated by the database from the person table.
     * Username and password are set by the admin in the form.
     * Returns the saved student with the generated ID set, or null on failure.
     */
    public Student addStudent(Student student) {
        String personSql  = "INSERT INTO person (name, age, email, phone) VALUES (?, ?, ?, ?)";
        String studentSql = "INSERT INTO student (id, course, roomId, status, username, password, regNumber) " +
                            "VALUES (?, ?, ?, ?, ?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection()) {
            conn.setAutoCommit(false);

            try (PreparedStatement ps1 = conn.prepareStatement(
                    personSql, Statement.RETURN_GENERATED_KEYS)) {

                ps1.setString(1, student.getName());
                ps1.setInt(2,    student.getAge());
                ps1.setString(3, student.getEmail());
                ps1.setString(4, student.getPhone());
                ps1.executeUpdate();

                ResultSet keys = ps1.getGeneratedKeys();
                if (keys.next()) {
                    String generatedId = String.valueOf(keys.getInt(1));
                    student.setId(generatedId);

                    try (PreparedStatement ps2 = conn.prepareStatement(studentSql)) {
                        ps2.setString(1, generatedId);
                        ps2.setString(2, student.getCourse());
                        ps2.setString(3, student.getRoomId());
                        ps2.setString(4, student.getStatus());
                        ps2.setString(5, student.getUsername());
                        ps2.setString(6, PasswordUtil.hash(student.getPassword()));
                        ps2.setString(7, student.getRegNumber());
                        ps2.executeUpdate();
                    }
                }

                conn.commit();
                return student;

            } catch (SQLException e) {
                conn.rollback();
                throw e;
            }

        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    // ── UPDATE ────────────────────────────────────────────────────────────────

    /**
     * Updates both person and student tables inside a transaction.
     * If password is null or blank on edit, existing password is kept unchanged.
     * Returns true if successful, false on failure.
     */
    public boolean updateStudent(Student student) {
        String personSql = "UPDATE person SET name=?, age=?, email=?, phone=? WHERE id=?";

        boolean changePassword = student.getPassword() != null && !student.getPassword().isEmpty();
        String studentSql = changePassword
            ? "UPDATE student SET course=?, roomId=?, status=?, username=?, password=?, regNumber=? WHERE id=?"
            : "UPDATE student SET course=?, roomId=?, status=?, username=?, regNumber=? WHERE id=?";

        try (Connection conn = DatabaseConnection.getConnection()) {
            conn.setAutoCommit(false);

            try (PreparedStatement ps1 = conn.prepareStatement(personSql);
                 PreparedStatement ps2 = conn.prepareStatement(studentSql)) {

                // person table
                ps1.setString(1, student.getName());
                ps1.setInt(2,    student.getAge());
                ps1.setString(3, student.getEmail());
                ps1.setString(4, student.getPhone());
                ps1.setString(5, student.getId());
                ps1.executeUpdate();

                // student table
                ps2.setString(1, student.getCourse());
                ps2.setString(2, student.getRoomId());
                ps2.setString(3, student.getStatus());
                ps2.setString(4, student.getUsername());
                if (changePassword) {
                    ps2.setString(5, PasswordUtil.hash(student.getPassword()));
                    ps2.setString(6, student.getRegNumber());
                    ps2.setString(7, student.getId());
                } else {
                    ps2.setString(5, student.getRegNumber());
                    ps2.setString(6, student.getId());
                }
                ps2.executeUpdate();

                conn.commit();
                return true;

            } catch (SQLException e) {
                conn.rollback();
                throw e;
            }

        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    // ── DELETE ────────────────────────────────────────────────────────────────

    /**
     * Deletes student row first (FK constraint), then person row.
     * Both wrapped in a transaction so either both succeed or both roll back.
     * Returns true if successful, false on failure.
     */
    public boolean deleteStudent(String id) {
        String deleteStudentSql = "DELETE FROM student WHERE id=?";
        String deletePersonSql  = "DELETE FROM person  WHERE id=?";

        try (Connection conn = DatabaseConnection.getConnection()) {
            conn.setAutoCommit(false);

            try (PreparedStatement ps1 = conn.prepareStatement(deleteStudentSql);
                 PreparedStatement ps2 = conn.prepareStatement(deletePersonSql)) {

                ps1.setString(1, id);
                ps1.executeUpdate();

                ps2.setString(1, id);
                ps2.executeUpdate();

                conn.commit();
                return true;

            } catch (SQLException e) {
                conn.rollback();
                throw e;
            }

        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
}